baseURL = "/"
languageCode = "en-us"
title = "Debris Field"
theme = "archie"
summaryLength = 20

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[[params.social]]
name = "Soundcloud"
icon = "headphones"
url = "https://soundcloud.com/debris_field/"

[params]
	mode="light"
	featherIconsCDN=true
	subtitle = ""

	[params.logo]
		url = "/images/logo.png"
		width = 350

[[menu.main]]
name = "Projects"
url = "/tags/project"
weight = 1

[[menu.main]]
name = "Fragments"
url = "/posts/fragments"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
